// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkEkcyhq2swIgSfaoHSpf0vAxgl5Xhao',
    appId: '1:1027220963414:web:3111bc0fb093b1a18f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    authDomain: 'beltei.firebaseapp.com',
    storageBucket: 'beltei.appspot.com',
    measurementId: 'G-RYBCST8RX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zBVe3DmhLcoaTbK0y58wiGXw4LgZuWM',
    appId: '1:1027220963414:android:27867160a6f59b758f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    storageBucket: 'beltei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tftCQAFSXhNGvlhoq4sAKeyWfXl_L24',
    appId: '1:1027220963414:ios:82699271f413c8458f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    storageBucket: 'beltei.appspot.com',
    androidClientId: '1027220963414-a8h21nimj2viu6ko5acvdt9td6o3cjsl.apps.googleusercontent.com',
    iosClientId: '1027220963414-ml0m11g2d442c06a3bp7i2mfqh79t21o.apps.googleusercontent.com',
    iosBundleId: 'kh.edu.beltei.mad.uc2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5tftCQAFSXhNGvlhoq4sAKeyWfXl_L24',
    appId: '1:1027220963414:ios:0f7bbecf17d74aa88f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    storageBucket: 'beltei.appspot.com',
    androidClientId: '1027220963414-a8h21nimj2viu6ko5acvdt9td6o3cjsl.apps.googleusercontent.com',
    iosClientId: '1027220963414-6hls0n1m074ot1vqrgum21cvb6ngf6c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mad2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgkEkcyhq2swIgSfaoHSpf0vAxgl5Xhao',
    appId: '1:1027220963414:web:3111bc0fb093b1a18f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    authDomain: 'beltei.firebaseapp.com',
    storageBucket: 'beltei.appspot.com',
    measurementId: 'G-RYBCST8RX6',
  );
}
